export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const PATIENT_DATA_REQUEST = 'PATIENT_DATA_REQUEST'
export const PATIENT_DATA_SUCCESS = 'PATIENT_DATA_SUCCESS'
export const PATIENT_DATA_FAIL = 'PATIENT_DATA_FAIL'
export const PATIENT_DATA_RESET = 'PATIENT_DATA_RESET'

export const PATIENT_RECORD_REQUEST = 'PATIENT_RECORD_REQUEST'
export const PATIENT_RECORD_SUCCESS = 'PATIENT_RECORD_SUCCESS'
export const PATIENT_RECORD_FAIL = 'PATIENT_RECORD_FAIL'
export const PATIENT_RECORD_RESET = 'PATIENT_RECORD_RESET'

export const PATIENT_FAMILY_REQUEST = 'PATIENT_FAMILY_REQUEST'
export const PATIENT_FAMILY_SUCCESS = 'PATIENT_FAMILY_SUCCESS'
export const PATIENT_FAMILY_FAIL = 'PATIENT_FAMILY_FAIL'
export const PATIENT_FAMILY_RESET = 'PATIENT_FAMILY_RESET'